# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0004_auto_20170806_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='img',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pro',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
