# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0005_auto_20170807_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
