# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0007_auto_20170808_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='art',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pro',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
